Algoritmo "funcao_Para_"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/06/2022
Var
a,v,resul:inteiro

Inicio

resul<-0

Para a<-1 ate 3 faca

escreval("")
escreva("Digite um valor ? ")
leia(v)
escreval("")

se (v>=0) e (v<=7)entao
resul<- resul + 1

fimse

fimPara
escreval("Foram digitados",resul," valores entre 0 e 7")

Fimalgoritmo