Algoritmo "PAR_OU_IMPAR"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/06/2022
Var
   C,N,ContDiv:Inteiro
inicio
   c<-1
   ContDiv<-0
   Escreva("Digite um numero:")
   Leia(N)
   Repita
      Escreva(c)
      Se (C&N=0) entao
         ContDiv<-ContDiv+1
      Fimse
      C<C+1
  Ate(CN)
   EscrevaL("Ao todo existem",ContDiv,"valores divisiveis.")

Fimalgoritmo