Algoritmo "pra_minha_bb"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/06/2022
Var
// Seção de Declarações das variáveis 
a,b,c:inteiro

Inicio

escreva("Escreva algo: ")
leia (b)
limpatela
escreval("")
escreval("Náo importa oq vc escreveu, EU TE AMO MUITO!")


para a:=1 ate 10 faca


escreval("MUITO")


fimpara

Fimalgoritmo