Algoritmo "seletor_de_pessoas"
// 

Var
idade,cabelo:inteiro
sexo: caractere

Inicio
escreval("=========================")
escreval("   SELETOR DE PESSOAS    ")
escreval("=========================")
escreva("Qual o sexo ? [M/F] ")
leia(sexo)
escreval("")
escreva("Qual idade ? ")
leia(idade)
escreval("")
escrevaL("Cor do cabelo ? ")
escreval("")
escreval("[1] Preto")
escreval("[2] Castanho")
escreval("[3] Loiro")
escreval("[4] Ruivo")
leia(cabelo)

se (sexo="M")entao













Fimalgoritmo