algoritmo "operadores"
   var
      num1 : inteiro
      num2 : inteiro
      bol1 : logico
      bol2 : logico
      text1 : caractere
      text2 : caractere
      Resultado : caractere
      dados : real
inicio
   num1 <- 77
   num2 <- 7
   bol1 <- verdadeiro
   bol2 <- falso
   text1 <- "Olá, "
   text2 <- "tudo bem ?"
   resultado <- text1 + text2
   escreval ("Escreva uma valor para a variável 'dados' ")
   leia (dados)



fimalgoritmo